### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [Ronak-LM/Watchlist#3]
Would you mind publishing the APK here at Github, preferably under `releases/` (see [Creating Releases](https://help.github.com/articles/creating-releases/) for details on how easy that is)? This would give users without Playstore access to your app as well :)

Thanks in advance!

**Comment by ronak-lm** [comment]
Added it. Thanks for letting me know! :+1:

**Comment by IzzySoft** [comment]
That was fast! Thanks a lot! :+1:

**Comment by IzzySoft** [comment]
Is this project still maintained? No commit in over 2 years, so I'm just wondering :wink:

**Comment by IzzySoft** [comment]
@Ronak-LM ^^?? No answer means "abandoned"?

**Comment by IzzySoft** [comment]
@Ronak-LM any chance for a clear statement?

**Comment by ronak-lm** [comment]
Yes, the project is not maintained. I've shifted my focus to backend development and hybrid apps. This was just a hobby project. Feel free to fork the repo and use it anyway you wish.

**Comment by IzzySoft** [comment]
Thanks for your reply, @Ronak-LM – that's a real pity. Hopefully nothing breaks. App still runs smooth and snappy, really like it. It's also available [in my F-Droid compatible repo](https://apt.izzysoft.de/fdroid/index/apk/com.ronakmanglani.watchlist); I've just updated the description pointing out the EOL (linking here; change goes live with the next sync in about 12 hours). I'm not an Android dev – so me forking it wouldn't help unfortunately. But if someone else wants to pick it up, it's good to know!

Just wondering: there were some commits after the last release. Would you mind building a "final version"? Us "privacy folks" would especially welcome that for 6850f1e :wink:

Meanwhile, all the best for your current and future projects!

**Comment by ronak-lm** [comment]
Thanks. I lost some interest after Play Store banned my app for using movie cover images. Some copyright issue. I might be building a version of this in React and React Native soon. Will put it up on GitHub...

**Comment by IzzySoft** [comment]
No such issues to be expected with my repo (well, if a copyright owner complains I might need to take action if proof is presented, but would then consult with you first if I get the time granted for that – and I'd remove apps if they suddenly introduced "risky things" like a bunch of trackers or something that triggers more than 4 malware scanners, for example; but always I'd be as fast re-establishing the listing as soon as the issues are solved).

So if your app being listed in my repo motivates you to pick up again, that would be great! New versions tagged with an APK attached would automatically show up in my repo within 24h. If you switch repos for some reason, ping me here to let me know where to pick up.

Oh, and if on the rewrite you'd leave out all proprietary components (like GA and GMS, which are currently in) and would like your app going to the [official F-Droid repo](https://f-droid.org/), I gladly assist you with that as well.
