### ISSUE TITLE
Reuse code with TextUtils

### ISSUE THREAD

**Issue by parkjaeiek** [Ronak-LM/Watchlist#4]
movie.backdropImage != null && !movie.backdropImage.equals("null")

isTextEmpty(movie.backdropImage)

make common util code better good

 public static boolean isTextEmpty(CharSequence text) {
        if (TextUtils.isEmpty(text)) {
            return true;
        } else {
            if ("null".equals(text)) {
                return true;
            } else {
                return false;
            }
        }
    }

**Comment by ostea** [comment]
👍  i think so,lolol

**Comment by ronak-lm** [comment]
Fixed it. Thanks for your suggestion...
