### ISSUE TITLE
google-services.json is missing

### ISSUE THREAD

**Issue by isaacdjx** [Ronak-LM/Watchlist#5]
Error:Execution failed for task ':app:processDebugGoogleServices'.

> File google-services.json is missing from module root folder. The Google Services Plugin cannot function without it.

**Comment by ronak-lm** [comment]
The file contains my app ID for google analytics. Pushing it to git can cause issues my analytics if someone else testing the app changes the tracked pages or events. Make sure you create your own account and replace the file if you want the analytics to show up in your dashboard. For more information check [CONTRIBUTING.md](https://github.com/Ronak-LM/Watchlist/blob/master/CONTRIBUTING.md)
