### ISSUE TITLE
Unable to get provider com.ronakmanglani.watchlist.database.generated.MovieProvider

### ISSUE THREAD

**Issue by josephpeters24** [Ronak-LM/Watchlist#9]
Tried to run this app but I always get this exception

**Comment by pavelsust** [comment]
It shows a error in manifest file but in my project it works you can try in android studio latest version. I am using it so I suggest it

**Comment by josephpeters24** [comment]
I already have the latest Version

**Comment by ronak-lm** [comment]
Hi,
That's a generated class and will be created when you build the project. It seems to be working fine here. Try to delete the build folders and run it again...

**Comment by josephpeters24** [comment]
That worked ! Thank you :) Btw really good project and nice code ! It is really useful to learn from
